In [1]:
import numpy as np

In [2]:
# creating array from list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


In [3]:
arr_2 = np.array([1, 2, 3, 4, 5, "Pranav"])
print(arr_2, type(arr_2), arr_2.shape)

['1' '2' '3' '4' '5' 'Pranav'] <class 'numpy.ndarray'> (6,)


In [4]:
# 2D-Array

arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2D, arr_2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
# Creating Arrays with Built-in Functions

# 1) np.zeros() - Creates an array filled with 0s.
arr1 = np.zeros((2, 3), dtype="int64")
print(arr1, arr1.shape)

# 2) np.ones() - Creates an array filled with 1s.
arr2 = np.ones((3,3))
print(arr2, arr2.shape)

# 3) np.full() - Creates an array filled with a specific constant value.
arr3 = np.full((3,4), 15)
print(arr3, arr3.shape)

# 4) np.eye() - Creates an identity matrix (1s on diagonal).
arr4 = np.eye(3)
print(arr4, arr4.shape)

# 5) np.arange() - Generates numbers in a range with a given step.
arr5 = np.arange(1, 11, 3)
print(arr5, arr5.shape)

# 6) np.linspace() - Generates evenly spaced values between start and end.
arr6 = np.linspace(0, 12, 3)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  4  7 10] (4,)
[ 0.  6. 12.] (3,)
