In [1]:
import numpy as np

In [2]:
arr = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

In [3]:
# Properties of array

# 1) shape : returns array dimensions (rows × columns)
print(f"Array Shape : {arr.shape}")

# 2) size : returns total number of elements in the array
print(f"Array Size : {arr.size}")

# 3) dtype : returns data type of array elements
print(f"Data Type of array : {arr.dtype}")

# 4) ndim : returns number of dimensions of the array
print(f"Array Dimension : {arr.ndim}")

# 5) astype : converts array into another data type
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

Array Shape : (3, 3)
Array Size : 9
Data Type of array : int64
Array Dimension : 2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [4]:
# Indexing
arr2 = np.array([1, 2, 3, 4, 5])

print("1D Array : ")
print(arr2[0], arr2[1], arr2[2])

# Indexing for 2D Array
print("2D Array : ")
print(arr[0][0], arr[0][1])
print(arr[1][0], arr[1][1])

# Fancy Indexing

idx = [0, 1, 3]
print(arr2[idx])

1D Array : 
1 2 3
2D Array : 
1 2
4 5
[1 2 4]


In [5]:
# Boolean Indexing

print(arr2[arr2 > 2])
print(arr2[arr2 <= 2])
print(arr2[arr2 % 2 == 0])
print(arr2[arr2 % 2 != 0])

[3 4 5]
[1 2]
[2 4]
[1 3 5]


In [6]:
# Sclicing

arr2 = np.array([1, 2, 3, 4, 5])

print(arr2[0:4])
print(arr2[1:])
print(arr2[2:5])
print(arr2[:])
print(arr2[::2])

[1 2 3 4]
[2 3 4 5]
[3 4 5]
[1 2 3 4 5]
[1 3 5]


In [7]:
# Multi-imensional Arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

# Slicing of 2D-Array
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [8]:
# 3D-Array

arr3D = np.array([ [[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]] ]) # 2 x 3 x 2
print(arr3D, arr3D.shape)

# indexing
print(arr3D[1, 0, 1])

# Slicing
print(arr3D[0:2, 2:3, 0:2])

print(arr3D[:, 0, :]) # first rows of both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
8
[[[ 5  6]]

 [[11 12]]]
[[1 2]
 [7 8]]


In [5]:
# Vectorization
# Vectorization refers to performing operations on entire array without using loops
# NumPy internally uses C-optimized code, so vectorized operations are much faster than Python loops.

# Normal Python
py_list = [1, 2, 3, 4, 5]
sq_list = [x**2 for x in py_list]
print(py_list, sq_list)

# With Vectorization
arr = np.array([1, 2, 3, 4, 5])
sq_arr = arr ** 2
print(f""sq_arr)

[1, 2, 3, 4, 5] [1, 4, 9, 16, 25]
[ 1  4  9 16 25]


In [9]:
# Broadcasting :
# Broadcasting allows NumPy to do arithmetic on arrays of different shapes by stretching the smaller array.

arr = np.array([1, 2, 3, 4, 5])
result = arr + 5
print(result)

arr2D = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr1D = np.array([10, 20, 30])
result = arr2D + arr1D
print(result)

[ 6  7  8  9 10]
[[11 22 33]
 [14 25 36]]


In [10]:
# Normalization
# Normalization means converting values into a standard scale without changing the pattern of the data.

# Types :

# 1) Min–Max Normalization :

'''
X_norm = (X − X_min) / (X_max − X_min)

'''
arr = np.array([10, 20, 30, 40, 50, 60])

x_min = arr.min()
x_max = arr.max()

normalized_arr = (arr - x_min)/(x_max - x_min)
print(normalized_arr)


# 2) Z-score (Standard) Normalization :
'''
Z = (X - σ) / μ

μ = mean
σ = standard deviation

'''

zscore = (arr - arr.mean()) / arr.std()
print(zscore)

[0.  0.2 0.4 0.6 0.8 1. ]
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
