In [1]:
import numpy as np

In [2]:
# Operations on Arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array Shape : {arr.shape}")  # shows original dimensions

reshaped_arr = arr.reshape((3, 2))  # reshapes array to 3 rows × 2 columns
print(f"Reshaped Array : \n{reshaped_arr}", reshaped_arr.shape)

flattened_arr = arr.flatten()  # converts array into a 1D array
print(f"Flattened Array : \n{flattened_arr}", flattened_arr.shape)

#--------------------------------------------------------------------

arr = np.array([3, -1, 2, 3, -5, 2, 4])
print("Array:", arr)

# np.unique() → returns unique elements
unique_arr = np.unique(arr)
print("Unique:", unique_arr)

# np.sort() → sorts the array
sorted_arr = np.sort(arr)
print("Sorted:", sorted_arr)

# np.abs() → absolute values
abs_arr = np.abs(arr)
print("Absolute:", abs_arr)

Array Shape : (2, 3)
Reshaped Array : 
[[1 2]
 [3 4]
 [5 6]] (3, 2)
Flattened Array : 
[1 2 3 4 5 6] (6,)
Array: [ 3 -1  2  3 -5  2  4]
Unique: [-5 -1  2  3  4]
Sorted: [-5 -1  2  2  3  3  4]
Absolute: [3 1 2 3 5 2 4]


In [3]:
arr2d = np.array([[3, -1, 2], [2, 3, -4]])
print("Original 2D Array:\n", arr2d)

# 1. np.unique()
print("\n")

# Unique elements (flattened)
print("Unique elements:", np.unique(arr2d))

# Unique along axis 0 (columns)
print("Unique along axis 0:\n", np.unique(arr2d, axis=0))

# Unique along axis 1 (rows)
print("Unique along axis 1:\n", np.unique(arr2d, axis=1))

#---------------------------------------------------------------

# 2. np.sort()
print("\n")

# Sort rows
print("Row-wise sorted:\n", np.sort(arr2d, axis=1))

# Sort columns
print("Column-wise sorted:\n", np.sort(arr2d, axis=0))

#---------------------------------------------------------------

# 3. np.abs()
print("\n")

# Absolute values
print("Absolute 2D array:\n", np.abs(arr2d))

Original 2D Array:
 [[ 3 -1  2]
 [ 2  3 -4]]


Unique elements: [-4 -1  2  3]
Unique along axis 0:
 [[ 2  3 -4]
 [ 3 -1  2]]
Unique along axis 1:
 [[-1  2  3]
 [ 3 -4  2]]


Row-wise sorted:
 [[-1  2  3]
 [-4  2  3]]
Column-wise sorted:
 [[ 2 -1 -4]
 [ 3  3  2]]


Absolute 2D array:
 [[3 1 2]
 [2 3 4]]
